language: ruby

rvm:
  - 2.7.1

before_script:
  - chmod +x ./build_scripts/cibuild

script: ./build_scripts/cibuild

before_install:
  - gem update --system
  - gem install bundler
  - gem install rake
  - gem install jekyll
  - gem install github-pages

branches:
  only:
    - master
    - develop

deploy:
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

sudo: false

cache: bundler

notifications:
  email: false
